import {
  BRow,
  BCol,
  BCard,
  BButton,
  BCardText,
  BFormRadio,
  BImg,
  BTable,
  BFormTextarea,
  BFormRadioGroup,
  BListGroup,
  BListGroupItem,
  BFormGroup,
  BFormSelect,
  BFormCheckbox,
  BInputGroup,
  BInputGroupText,
  BInputGroupAppend,
  BInputGroupPrepend,
  BFormInput,
  BDropdown,
  BDropdownItem,
} from 'bootstrap-vue'

export default {
  components: {
    BRow,
    BFormTextarea,
    BDropdown,
    BDropdownItem,
    BFormCheckbox,
    BInputGroup,
    BInputGroupText,
    BInputGroupAppend,
    BInputGroupPrepend,
    BFormRadioGroup,
    BButton,
    BImg,
    BTable,
    BFormRadio,
    BCard,
    BFormSelect,
    BCardText,
    BListGroup,
    BListGroupItem,
    BCol,
    BFormGroup,
    BFormInput,
  },
}
